name: componentm
synopsis: Monad for allocation and cleanup of application resources
description: |
  This library allows you to allocate resources with
  clean up strategies when initializing your application.
  It then provides a Monadic interface to compose multiple
  resources without having to deal with cleanup operations
  explicitely.

version: '0.0.0.2'
category: System
author: Roman Gonzalez
maintainer: open-source@roman-gonzalez.info
copyright: © 2017-current Roman Gonzalez
license: MIT
github: roman/Haskell-componentm
tested-with: GHC==8.0.1 GHC==8.0.2 GHC==8.2.1
extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
# as recommended in:
# https://functor.tokyo/blog/2017-07-28-ghc-warnings-you-should-enable
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates

dependencies:
- base >=4.8 && <5
- rio >= 0.0.3
- containers >= 0.5.7
- teardown >= 0.5
- prettyprinter >= 1.1
- pretty-show >= 1.6.13

library:
  source-dirs: src
  exposed-modules:
  - Control.Monad.Component
  - Control.Monad.Component.Internal.Types
  - Control.Monad.Component.Internal.Core
  dependencies:
  - exceptions >= 0.8.3
  - deepseq >= 1.4.2

tests:
  componentm-tests:
    main: TestSuite.hs
    source-dirs: test/tasty
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty >= 0.11.2
    - tasty-hunit >= 0.9.2
    - componentm

stability: alpha (experimental)
